data_science/auto-ai/shell/webinterface/models.py
from controllers.user.models import *

data_science/auto-ai/shell/webinterface/controllers/main.py
import os

from flask import (
    Blueprint, current_app, jsonify, render_template, abort, request)
from werkzeug.utils import secure_filename

from core.data import AutoAiDAL, AutoAiDataExplorer
from core.jobs.AutoAiJobRunner import AutoAiJobRunner
from core.modeling.ModelTrainingGenerator import ModelTrainingGenerator
from core.utils.AutoAiLogger import AutoAiLogger

main = Blueprint('main', __name__)


class UiState(object):
    logger = AutoAiLogger('UI')
    dal = None
    data_explorer = None
    model_gen = None
    job_runner = AutoAiJobRunner()


current_ui_state = UiState()

INITIAL_PROJECTS = [
    { 'id': 0,
      'name': 'Ticket Routing'
    },{ 'id': 1,
      'name': 'Failure Detection'
    },{ 'id': 2,
      'name': 'Churn Prediction'
    },
]


@main.route('/')
def index():
    return render_template('main/index.html')


@main.route('/projects')
def projects():
    return render_template('main/projects.html',
                           projects=INITIAL_PROJECTS)


@main.route('/add_project', methods=['POST'])
def add_project():
    new_project = dict(
        id=request.form.get('id', type=int),
        name=request.form.get('name')
    )
    INITIAL_PROJECTS.append(new_project)
    return "Success"


@main.route('/upload_data/')
@main.route('/upload_data/<int:project_id>')
def upload_data(project_id=None):
    if project_id is not None:
        the_project = next(p for p in INITIAL_PROJECTS
                           if p["id"] == project_id)
        return render_template('main/upload_data.html',
                               current_project=the_project)
    else:
        abort(404)


@main.route('/project_config/')
@main.route('/project_config/<int:project_id>', methods=['GET', 'POST'])
def project_config(project_id=None):
    if project_id is not None:
        the_project = next(p for p in INITIAL_PROJECTS
                           if p["id"] == project_id)
        # project_name = the_project['name']
        # dal = AutoAiDAL(
        #    project_name,
        #    os.path.join(project_dir, 'test', 'datasets'))

        project_home_dir = '/tmp'
        project_name = the_project['name']
        if the_project['name'].lower() == 'titanic':
            project_home_dir = current_app.config['DEV_TEST_DS_DIR']
            current_ui_state.dal = AutoAiDAL.AutoAiDAL(
                project_name, project_home_dir)
            # (NOTE:tonytan4ever) for now hardcode to load up titanic's
            # dataframe
            df = current_ui_state.dal.load_csv_file('titanic_train.csv')
            current_ui_state.data_explorer = AutoAiDataExplorer.AutoAiDataExplorer(
                project_name, df)
        else:
            # save the file
            data_file = request.files['data_file']
            filename = secure_filename(data_file.filename)
            file_dst_path = os.path.join(project_home_dir, filename)
            data_file.save(file_dst_path)

            current_ui_state.dal = AutoAiDAL.AutoAiDAL(
                project_name, project_home_dir)
            df = current_ui_state.dal.load_csv_file(filename)
            current_ui_state.data_explorer = (
                AutoAiDataExplorer.AutoAiDataExplorer(project_name, df))

        return render_template('main/project_config.html',
                               current_project=the_project,
                               data_explorer=current_ui_state.data_explorer
                               )
    else:
        abort(404)


@main.route('/start_training/<int:project_id>')
@main.route('/start_training/<int:project_id>', methods=['GET', 'POST'])
def start_training(project_id=None):
    if project_id is not None:
        the_project = next(p for p in INITIAL_PROJECTS if p["id"] == project_id)
        if request.method.lower() == "post":
            form_items = dict(request.form.items())
            current_ui_state.logger.debug(f'start_training form_items={form_items}')
            training_cfg = dict()
            training_cfg['model_selection_metric'] = form_items['model_selection_metric']
            training_cfg['training_type'] = form_items['training_type']
            training_cfg['training_number'] = 20    # advanced options later in UI
            training_cfg['n_iter_search'] = 200     # advanced options later in UI
            training_cfg['validation_size'] = 0.20  # advanced options later in UI
            training_cfg['simulate_jobs'] = True    # set to false to run real jobs (not test UI)
            current_ui_state.logger.debug(f'training_cfg={training_cfg}')

            current_ui_state.data_explorer.set_as_target(form_items['target_row'])
            current_ui_state.data_explorer.set_as_index(form_items['index_row'])
            current_ui_state.data_explorer.set_as_weight(form_items['weight_row'])
            current_ui_state.logger.debug(
                f'training target/index/weight columns: {form_items["target_row"]}/{form_items["index_row"]}/{form_items["weight_row"]}')

            current_ui_state.model_gen = ModelTrainingGenerator(
                current_ui_state.data_explorer, training_cfg,
                current_ui_state.job_runner, random_state=123)
            current_ui_state.model_gen.run_jobs()

        return "Okay"
    else:
        abort(404)


@main.route('/start_testing/<int:project_id>')
@main.route('/start_testing/<int:project_id>', methods=['GET', 'POST'])
def start_testing(project_id=None):
    if project_id is not None:
        the_project = next(p for p
                           in INITIAL_PROJECTS if p["id"] == project_id)
        return render_template('main/start_testing.html',
                               current_project=the_project)
    else:
        abort(404)


@main.route('/training_summary/')
@main.route('/training_summary/<int:project_id>')
def training_summary(
        project_id=None,
):
    if project_id is not None:
        the_project = next(p for p in INITIAL_PROJECTS if p["id"] == project_id)
        current_job_runner_progress = current_ui_state.job_runner.get_status()
        current_job_runner_results = current_ui_state.job_runner.get_results()
        return render_template('main/training_summary.html',
                               current_job_runner_progress=current_job_runner_progress,
                               current_job_runner_results=current_job_runner_results,
                               current_project=the_project)
    else:
        abort(404)


@main.route('/training_job_update')
def training_job_update():

    current_job_runner_progress = current_ui_state.job_runner.get_status()
    current_job_runner_results = current_ui_state.job_runner.get_results()

    print(f'###### JobRunner status={current_job_runner_progress}')
    print(f'###### JobRunner results={current_job_runner_results}')

    return jsonify({
        'status': 'success',
        'training_job_status': current_job_runner_progress,
        'training_job_results': current_job_runner_results
    })


@main.route('/predict/')
@main.route('/predict/<int:project_id>')
def predict(project_id=None):
    if project_id is not None:
        the_project = next(p for p in INITIAL_PROJECTS
                           if p["id"] == project_id)
        return render_template('main/upload_test_data.html',
                               current_project=the_project)
    else:
        abort(404)

data_science/auto-ai/shell/webinterface/controllers/user/__init__.py
from shell.webinterface.controllers.user.views import user

data_science/auto-ai/shell/webinterface/controllers/user/views.py
from flask import (Blueprint, render_template, flash, request, redirect, url_for,
                   current_app)

user = Blueprint('user', __name__)


@user.route('/profile')
def profile():
    social = current_app.extensions['social']
    return render_template(
        'user/profile.html',
        #content='Profile Page',
        #twitter_conn=social.twitter.get_connection(),
        #facebook_conn=social.facebook.get_connection()
        #foursquare_conn=social.foursquare.get_connection()
        )

data_science/auto-ai/shell/webinterface/templates/401.html
{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for_security('login')}}">log in</a> or
            <a href="{{ url_for_security('register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

data_science/auto-ai/shell/webinterface/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>{{ full_name }}</li>
  </ul>

    <ul class="footer-nav">
      <li><a href="url_for('public.about')">About</a></li>
      <li><a href="">Contact</a></li>
    </ul>
  </small>
</footer>

data_science/auto-ai/shell/webinterface/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}
    	 {% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">
  
  <link rel="shortcut icon" href="{{ url_for('static', filename='images/icon-ai-data-analytics.png') }}">

  <link rel="stylesheet" href="{{ url_for('static', filename='libs/font-awesome4/css/font-awesome.min.css') }}">
  {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}

  {% block css %}{% endblock %}

</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
{% with form=form  %}
{% include "nav.html" %}
{% endwith %}

<header>{% block header %}{% endblock %}</header>
<div class="{% block content_class %}container{% endblock content_class %}">

  <div role="main">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{message}}
        </div><!-- end .alert -->
        {% endfor %}
      </div><!-- end col-md -->
    </div><!-- end row -->
    {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
  </div>

</div><!-- end container -->

<!-- JavaScript at the bottom for fast page loading -->
{% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}
</body>
</html>

data_science/auto-ai/shell/webinterface/templates/main/project_config.html
{% extends "layout.html" %}

{% block page_title %}
Training Config       
{% endblock %}


{% block content %}
<script id="selectTmpl" type="text/x-jsrender"><div class="col-sm-4">
       {% raw %}
       <input class="df_select" type="checkbox" name="{{:field_name}}" value="{{:field_value}}" var_name="{{:var_name}}"><br>
       {% endraw %}
</script>

<div class="body-content">
    <div class="row">
        <h2>Data Exploration  &nbsp <a id='' href="#"><i class="fa fa-plus"></i></a></h2>
    </div>
    
    <div class="row">
       <h5>Training Configuration</h5>
       
       <div class="btn-group">
		  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		    Training Type <span class="caret"></span>
		  </button>
		  <ul class="dropdown-menu" role="menu">
		    <li><a href="#">Classification</a></li>
		    <li><a href="#">Regression</a></li>
		  </ul>
	   </div>
    
       <!--  <div class="btn-group">
		  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            Loss function <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
       </div> -->
          
       <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            Model Selection Metric <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">AUC</a></li>
            <li><a href="#">Accuracy</a></li>
          </ul>
	   </div>
    

    <div class="row">
    
	    <table id="grid-data" class="table table-condensed table-hover table-striped">
		    <thead>
		        <tr>
		            <th data-column-id="target_selected" data-formatter="html_widget">Target</th>
                    <th data-column-id="index_selected" data-formatter="html_widget">Index</th>
                    <th data-column-id="weight_selected" data-formatter="html_widget">Weight</th>
		            
		            <th data-column-id="var_name">Name</th>
		            <th data-column-id="var_type">Type</th>
		            <th data-column-id="missing"  data-type="numeric">Missing</th>
		            <th data-column-id="unique"  data-type="numeric">Unique</th>
		            <th data-column-id="mean_mode"  data-type="numeric">Mean/Mode</th>
		            <th data-column-id="min"  data-type="numeric">Min</th>
		            <th data-column-id="max"  data-type="numeric">Max</th>
		        </tr>
		    </thead>
		    <tbody>
		        {% for summary_key in data_explorer.summary %}
		        {% set summary_key_s_value = data_explorer.summary[summary_key] %}
		        <tr>
		            <td><input type="checkbox" name="target" value="target"><br></td>
		            <td><input type="checkbox" name="index" value="index"><br></td>
		            <td><input type="checkbox" name="weight" value="weight"><br></td>
		            <td>{{ summary_key }}</td>
		            <td>{{ summary_key_s_value.type }}</td>
		            <td>{{ summary_key_s_value.missing }}</td>
		            <td>{{ summary_key_s_value.unique }}</td>
		            <td>{{ summary_key_s_value.mean }}</td>
		            <td>{{ summary_key_s_value.min }}</td>
		            <td>{{ summary_key_s_value.max }}</td>
		        </tr>
		        {% endfor %}
	        </tbody>
	    </table>
	    
	    <div class="btn-group">
	       <button type="button" class="btn btn-primary" id="start_traiinng">
            Start Training
           </button>
        </div>
    </div>
</div>
{% endblock %}


{% block js %}
<script>
$(function() {
	var model_config_dict = {};
	
	$("#grid-data").bootgrid({
		rowCount: 15,
		formatters: {
	        html_widget: function (column, row){
	        	    var column_id_split = column.id.split('_')
	        	    var tmpl = $.templates("#selectTmpl"); // Get compiled template
                 var data = {
            		   field_name: column_id_split[0],
            		   field_value: column_id_split[0],
            		   var_name: row.var_name
                 };
                 var html = tmpl.render(data);
	            /* "this" is mapped to the grid instance */
	            
	            return html;
	        }
	    }
	}).on("loaded.rs.jquery.bootgrid", function (e){
		$("input.df_select").click(function(){
			var that = this;
			
	        if( $(this).is(':checked') ) {
	            var param_name = $(this).attr("name");
	            var var_name = $(this).attr("var_name");
	            
	            if($("input.df_select[name!='" + param_name + "'][var_name='" + var_name + "']").is(':checked')){
	            	  BootstrapDialog.show({
	            		  title: 'Invalid Model Configuration',
	            		  message: "You can't config target/index/weight like this..."
	            	  });
	            	  $(this).prop('checked', false);
	            	  return
	            } else {     
		            $("input.df_select[name='" + param_name + "']").prop('checked', false);
		            $(this).prop('checked', true);
		            model_config_dict[param_name+'_row'] = var_name;
	            }

	        };
	    })
    });
	
	$(".dropdown-menu li a").click(function(){
		  var selText = $(this).text();
		  var parent_button = $(this).parents('.btn-group').find('button[data-toggle="dropdown"]');
		  param_name = (parent_button.text().toLowerCase().trim().split(" ").join("_"));
		  model_config_dict[param_name] = selText.toLowerCase();
		  $(this).parents('.btn-group').find('button[data-toggle="dropdown"]').html(selText+' <span class="caret"></span>');
	});

	$("#start_traiinng").click(function(){
		
		console.log(model_config_dict);
		var required_config_options = [
		  "target_row", "index_row", "weight_row", 
		  "training_type", "model_selection_metric"	  
		], missing_options = [];
		
		$.each(required_config_options, function(index, val){
			if(!(val in model_config_dict)){
			    missing_options.push(val);
			}
		})

		if(missing_options.length > 0){
			BootstrapDialog.show({
                title: 'Invalid Model Configuration',
                message: "Missing (required) config option: <b>" + missing_options.join(',') + "</b>"
            });
		} else {
	        $.ajax({
	        	   method: 'post',
	        	   url: "{{ url_for('main.start_training', project_id=current_project.id) }}",
	        	   data: model_config_dict
	        }).done(function(){
	            location.replace("{{ url_for('main.training_summary')}}" + "{{ current_project.id }}");
	        })
		}

	});
	
	
});
</script>
{% endblock %}

data_science/auto-ai/shell/webinterface/templates/main/projects.html
{% extends "layout.html" %}

{% block page_title %}
Projects         
{% endblock %}

{% block css %}
<style>
.project-card {
  background-color: #eee;
}
</style>
{% endblock %}

{% block content %}
<div class="body-content">
    <script id="projTmpl" type="text/x-jsrender"><div class="col-sm-4">
       {% raw %}
       <div class="project-card" style="height:200px; width:70%; margin-top: 100px" project_id='{{:id}}'>
             <h4>{{:name}}</h4>
       {% endraw %}
             <p>{{ x | default(0) }} models deployed</p>
             <img  class="project-card" src="{{ url_for('static', filename='images/MyPlot.png') }}" height="100%" width="100%" ></img>
          </div>
       </div>
    </script>

    <div class="row">
        <h2>Projects  &nbsp <a id='add-project' href="#"><i class="fa fa-plus"></i></a></h2>
    </div>
    <div class="row" id='project-row'>
       {% for project in projects %}
       <div class="col-sm-4">
          <div class="project-card" style="height:200px; width:70%; margin-top: 100px" project_id='{{ project.id }}'>
             <h4>{{ project.name }}</h4>
             <p>{{ x | default(0) }} models deployed</p>
             <img  class="project-card" src="{{ url_for('static', filename='images/MyPlot.png') }}" height="100%" width="100%" ></img>
          </div>
       </div>
       {% endfor %}
    </div>
</div>
{% endblock %}

{% block js %}
<script>
$(function() {
	window.max_project_id = parseInt("{{ projects | length }}");
    $("a#add-project").click(function(){
	    	BootstrapDialog.show({
	    		    title: 'Project Info',
	    		    message: 'Project Name: <input type="text" id="project-name" class="form-control">',
	            buttons: [{
	                label: 'Add Project',
	                // no title as it is optional
	                cssClass: 'btn-primary',
	                data: {
	                    
	                },
	                action: function(dialogItself){
	                	   var tmpl = $.templates("#projTmpl"); // Get compiled template
	                    var data = {
	                    		name: $("input#project-name").val(),
	                    		id: window.max_project_id
	                		};           
	                    // render the new project's frontend template
	                    var html = tmpl.render(data);      // Render template using data - as HTML string
	                    // add project to the backend
	                    $.ajax({
                            method: 'post',
                            url: "{{ url_for('main.add_project') }}",
                            data: data
                        }).done(function(){
                            console.log('Project added...')
                            // add the new card frontend html for the project
                            $('div#project-row').append($(html));
                            $('div.project-card').click(function(){
                               // console.log(this.attr('project_id'));
                               location.replace("{{ url_for('main.upload_data')}}" + $(this).attr('project_id'));
                            })
                            window.max_project_id += 1;

                            dialogItself.close();
                        	 
                        }).fail(function(){
                        	   alert( "Fail to add project" );
                        	
                        });
	                }
	            }, {
	                label: 'Close',
	                action: function(dialogItself){
	                    dialogItself.close();
	                }
	            }]
	        });
    	
    })
    
    $("div.project-card").click(function(){
    	   // console.log(this.attr('project_id'));
    	   location.replace("{{ url_for('main.upload_data')}}" + $(this).attr('project_id'));
    })
});
</script>
{% endblock %}

data_science/auto-ai/shell/webinterface/templates/main/training_summary.html
{% extends "layout.html" %}

{% block page_title %}
Training Summary
{% endblock %}


{% block content %}
<div class="body-content">
    <div class="row">
        <h2>Training Summary </h2>
        Progress:
        <div class="progress">
            {% set proc_progress = 0 %}
            {% set proc_progress_str = "0%" %}
            {% if current_job_runner_progress.submitted >= 0 %}
                {% set proc_progress = (current_job_runner_progress.completed / current_job_runner_progress.submitted) * 100 %}
                {% set proc_progress_str = ('%0.1f' % proc_progress)|float|string + "%" %}
                {% set sub_str = current_job_runner_progress.submitted|int|string %}
                {% set cmp_str = current_job_runner_progress.completed|int|string %}
                {% set all_progress_str = ('%s (%s/%s)' % (proc_progress_str, sub_str, cmp_str)) %}
            {% endif %}
		    <div class="progress-bar" id="progress" style="width: {{ proc_progress_str }}%;">
		        {{ all_progress_str }}
		    </div>
		</div>
    </div>
    
    
    <div id="accordion" class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h5 class="panel-title">
               <span><a href="#collapseHeader">Model</a>
               <a href="#" style='float:right'>Validation Metrics</a>
               </span>
            </h5>
        </div>
    </div>
    {% for results in current_job_runner_results %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <span><a data-toggle="collapse" data-parent="#accordion" href="#{{ results.label }}">{{ results.label }}</a>
                <a href="#" style='float:right;pointer-events: none;cursor: default;color: inherit;'>{{ results.results }}</a>
                </span>
            </h4>
        </div>
        <div id="{{ model_name }}" class="panel-collapse collapse">
            <div class="panel-body">
                <p>Model Graph here</p>
                <div class="btn-group">
                    <a class="btn btn-primary" href="{{ url_for('main.predict', project_id=current_project.id) }}">Predict</a>
                    <a class="btn btn-default">Deploy</a>
                </div>
            </div>
        </div>
    </div>   
    {% endfor %}
</div>


</div>
{% endblock %}


{% block js %}
<script>
$(function() {
	setInterval(function(){ 
		$.ajax({
	         method: 'get',
	         url: "{{ url_for('main.training_job_update')}}",
	     }).success(function(response){
	         if(response.status == "success"){
	        	    var progress_percent = (
	        	    		response.training_job_status.completed * 100 / response.training_job_status.submitted).toFixed(1);
	        	    $("div#progress").width(progress_percent + "%");
	        	    $("div#progress").text(progress_percent + "%");
	        	    console.log(response.training_job_results)
	        	    for (result in response.training_job_results) {
	        	        $("span#panel-title").text(result.label);
	        	        $("span#panel-title").text(result.results);
	        	    }
	         }
	     })
		}, 5000);
});
</script>
{% endblock %}

data_science/auto-ai/shell/webinterface/templates/main/upload_data.html
{% extends "layout.html" %}

{% block page_title %}
Uplodate Data         
{% endblock %}

{% block css %}
<style>
.btn-file {
  position: relative;
  overflow: hidden;
}
.btn-file input[type=file] {
  position: absolute;
  top: 0;
  right: 0;
  min-width: 100%;
  min-height: 100%;
  font-size: 999px;
  text-align: right;
  filter: alpha(opacity=0);
  opacity: 0;
  background: red;
  cursor: inherit;
  display: block;
}
input[readonly] {
  background-color: white !important;
  cursor: text !important;
}
.bottom {
    padding-top: 10px
}
</style>
{% endblock %}

{% block content %}
<div class="body-content">
    <div class="row">
        <h2>Upload Data  &nbsp <a id='' href="#"><i class="fa fa-plus"></i></a></h2>
    </div>
    
    <div class="row">
        <form id="data-upload" method='post' action="{{ url_for('main.project_config', project_id=current_project.id) }}" enctype="multipart/form-data">
	    <div class="input-group">
		  <span class="input-group-btn">
		    <span class="btn btn-default btn-file">
		      Browse... 
		      <input data-url="/upload" name="data_file" accept=".csv"  type="file" id="data_file">
		    </span>
		  </span>
		  <input readonly="readonly" placeholder="Data File" class="form-control" name="filename" type="text">
		</div>
		</form>
	</div>
	<div class="row bottom">
	     <h5>Or import from:</h5>
	     <div class="btn-group">
		  <button type="button" class="btn btn-primary">ODBC</button>
		  <button type="button" class="btn btn-primary">HDFS</button>
		  <button type="button" class="btn btn-primary">Other</button>
		</div>
	</div>
</div>
{% endblock %}


{% block js %}
<script>
$(function() {
	$('input#data_file').change(function(){
		   console.log("file selected");
		   $('form#data-upload').submit();
	})
});
</script>
{% endblock %}

data_science/auto-ai/shell/webinterface/templates/main/upload_test_data.html
{% extends "layout.html" %}

{% block page_title %}
Uplodate Data         
{% endblock %}

{% block css %}
<style>
.btn-file {
  position: relative;
  overflow: hidden;
}
.btn-file input[type=file] {
  position: absolute;
  top: 0;
  right: 0;
  min-width: 100%;
  min-height: 100%;
  font-size: 999px;
  text-align: right;
  filter: alpha(opacity=0);
  opacity: 0;
  background: red;
  cursor: inherit;
  display: block;
}
input[readonly] {
  background-color: white !important;
  cursor: text !important;
}
.bottom {
    padding-top: 10px
}
</style>
{% endblock %}

{% block content %}
<div class="body-content">
    <div class="row">
        <h2>Upload Test Data  &nbsp <a id='' href="#"><i class="fa fa-plus"></i></a></h2>
    </div>
    
    <div class="row">
        <form id="data-upload" method='post' action="{{ url_for('main.start_testing', project_id=current_project.id) }}" enctype="multipart/form-data">
	    <div class="input-group">
		  <span class="input-group-btn">
		    <span class="btn btn-default btn-file">
		      Browse... 
		      <input data-url="/upload" name="data_file" type="file" id="data_file">
		    </span>
		  </span>
		  <input readonly="readonly" placeholder="Data File" class="form-control" name="filename" type="text">
		</div>
		</form>
	</div>
	<div class="row bottom">
         <h5>Or import from:</h5>
         <div class="btn-group">
          <button type="button" class="btn btn-primary">ODBC</button>
          <button type="button" class="btn btn-primary">HDFS</button>
          <button type="button" class="btn btn-primary">Other</button>
        </div>
    </div>
</div>
{% endblock %}


{% block js %}
<script>
$(function() {
	$('input#data_file').change(function(){
		   console.log("file selected");
		   $('form#data-upload').submit();
	})
});
</script>
{% endblock %}

data_science/auto-ai/shell/webinterface/templates/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{{ url_for('main.projects') }}">
      {{project_name}}
    </a>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><a href="{{ url_for('main.projects') }}">Projects</a></li>
    </ul>
    {% if current_project %}
    <ul class="nav navbar-nav navbar-right">
      <li>
          <a href="#">Project: {{ current_project.name }}</a>
      </li>
    </ul>
    {% endif %}
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>